/*
 *
 * Dashboard constants
 *
 */

export const DEFAULT_ACTION = 'app/HomePage/DEFAULT_ACTION';

export const DASHBOARD_GENERATOR = 'app/Dashboard/DASHBOARD_GENERATOR';

// <============================OVERVIEW=================================
export const GET_PROJECT_OVERVIEW_PATTERN =
  'app/Dashboard/GET_PROJECT_OVERVIEW_PATTERN';
export const GET_PROJECT_OVERVIEW_SUCCESS =
  'app/Dashboard/GET_PROJECT_OVERVIEW_SUCCESS';
export const GET_PROJECT_OVERVIEW_FAILIURE =
  'app/Dashboard/GET_PROJECT_OVERVIEW_FAILIURE';
export const CANCEL_GET_PROJECT_OVERVIEW_API_TASK =
  'app/Dashboard/CANCEL_GET_PROJECT_OVERVIEW_API_TASK';

export const GET_PROJECT_GLOBAL_VALUATION_PATTERN =
  'app/Dashboard/GET_PROJECT_GLOBAL_VALUATION_PATTERN';
export const GET_PROJECT_GLOBAL_VALUATION_SUCCESS =
  'app/Dashboard/GET_PROJECT_GLOBAL_VALUATION_SUCCESS';
export const GET_PROJECT_GLOBAL_VALUATION_FAILIURE =
  'app/Dashboard/GET_PROJECT_GLOBAL_VALUATION_FAILIURE';
export const CANCEL_GET_PROJECT_GLOBAL_VALUATION_API_TASK =
  'app/Dashboard/CANCEL_GET_PROJECT_GLOBAL_VALUATION_API_TASK';

// <============================ANALYTICS VIEWS=================================

export const ANALYTICS_VIEWS_PATTERN = 'app/Dashboard/ANALYTICS_VIEWS_PATTERN';
export const ANALYTICS_VIEWS_SUCCESS = 'app/Dashboard/ANALYTICS_VIEWS_SUCCESS';
export const ANALYTICS_VIEWS_FAILIURE =
  'app/Dashboard/ANALYTICS_VIEWS_FAILIURE';
export const CANCEL_ANALYTICS_VIEWS_API_TASK =
  'app/Dashboard/CANCEL_ANALYTICS_VIEWS_API_TASK';


// <============================ANALYTICS GLOBAL MARKETS=================================

export const ANALYTICS_GLOBAL_PATTERN = 'app/Dashboard/ANALYTICS_GLOBAL_PATTERN';
export const ANALYTICS_GLOBAL_SUCCESS = 'app/Dashboard/ANALYTICS_GLOBAL_SUCCESS';
export const ANALYTICS_GLOBAL_FAILIURE =
  'app/Dashboard/ANALYTICS_GLOBAL_FAILIURE';
export const CANCEL_ANALYTICS_GLOBAL_API_TASK =
  'app/Dashboard/CANCEL_ANALYTICS_GLOBAL_API_TASK';


// <============================MAIN GRAPH STATS=================================

export const VISION_STATS_PATTERN = 'app/Dashboard/VISION_STATS_PATTERN';
export const VISION_STATS_SUCCESS = 'app/Dashboard/VISION_STATS_SUCCESS';
export const VISION_STATS_FAILIURE = 'app/Dashboard/VISION_STATS_FAILIURE';
export const CANCEL_VISION_STATS_API_TASK =
  'app/Dashboard/CANCEL_VISION_STATS_API_TASK';

export const BRANDS_STATS_PATTERN = 'app/Dashboard/BRANDS_STATS_PATTERN';
export const BRANDS_STATS_SUCCESS = 'app/Dashboard/BRANDS_STATS_SUCCESS';
export const BRANDS_STATS_FAILIURE = 'app/Dashboard/BRANDS_STATS_FAILIURE';
export const CANCEL_BRANDS_STATS_API_TASK =
  'app/Dashboard/CANCEL_BRANDS_STATS_API_TASK';

export const MODELS_STATS_PATTERN = 'app/Dashboard/MODELS_STATS_PATTERN';
export const MODELS_STATS_SUCCESS = 'app/Dashboard/MODELS_STATS_SUCCESS';
export const MODELS_STATS_FAILIURE = 'app/Dashboard/MODELS_STATS_FAILIURE';
export const CANCEL_MODELS_STATS_API_TASK =
  'app/Dashboard/CANCEL_MODELS_STATS_API_TASK';

export const ASSETS_STATS_PATTERN = 'app/Dashboard/ASSETS_STATS_PATTERN';
export const ASSETS_STATS_SUCCESS = 'app/Dashboard/ASSETS_STATS_SUCCESS';
export const ASSETS_STATS_FAILIURE = 'app/Dashboard/ASSETS_STATS_FAILIURE';
export const CANCEL_ASSETS_STATS_API_TASK =
  'app/Dashboard/CANCEL_ASSETS_STATS_API_TASK';

export const VENUES_STATS_PATTERN = 'app/Dashboard/VENUES_STATS_PATTERN';
export const VENUES_STATS_SUCCESS = 'app/Dashboard/VENUES_STATS_SUCCESS';
export const VENUES_STATS_FAILIURE = 'app/Dashboard/VENUES_STATS_FAILIURE';
export const CANCEL_VENUES_STATS_API_TASK =
  'app/Dashboard/CANCEL_VENUES_STATS_API_TASK';

// <============================TIMELINE GRAPH STATS=================================

export const TIMELINE_PULSE_PATTERN = 'app/Dashboard/TIMELINE_PULSE_PATTERN';
export const TIMELINE_PULSE_SUCCESS = 'app/Dashboard/TIMELINE_PULSE_SUCCESS';
export const TIMELINE_PULSE_FAILIURE = 'app/Dashboard/TIMELINE_PULSE_FAILIURE';
export const CANCEL_TIMELINE_PULSE_API_TASK =
  'app/Dashboard/CANCEL_TIMELINE_PULSE_API_TASK';

export const TIMELINE_CUMULATIVE_PATTERN =
  'app/Dashboard/TIMELINE_CUMULATIVE_PATTERN';
export const TIMELINE_CUMULATIVE_SUCCESS =
  'app/Dashboard/TIMELINE_CUMULATIVE_SUCCESS';
export const TIMELINE_CUMULATIVE_FAILIURE =
  'app/Dashboard/TIMELINE_CUMULATIVE_FAILIURE';
export const CANCEL_TIMELINE_CUMULATIVE_API_TASK =
  'app/Dashboard/CANCEL_TIMELINE_CUMULATIVE_API_TASK';

// <============================CONTINOUS EXP=================================

export const CONTINOUS_EXP_PATTERN = 'app/Dashboard/CONTINOUS_EXP_PATTERN';
export const CONTINOUS_EXP_SUCCESS = 'app/Dashboard/CONTINOUS_EXP_SUCCESS';
export const CANCEL_CONTINOUS_EXP_API_TASK =
  'app/Dashboard/CANCEL_CONTINOUS_EXP_API_TASK';

// <============================GLOBAL FILTERS (TAGS)=================================

export const FILTER_TAGS_PATTERN = 'app/Dashboard/FILTER_TAGS';
export const FILTER_TAGS_SUCCESS = 'app/Dashboard/FILTER_TAGS_SUCCESS';
export const CANCEL_FILTER_TAGS_API_TASK =
  'app/Dashboard/CANCEL_FILTER_TAGS_API_TASK';

// <============================GLOBAL FILTERS (VISIONS)=================================

export const VISION_FILTER_PATTERN = 'app/Dashboard/VISION_FILTER';
export const VISION_FILTER_SUCCESS = 'app/Dashboard/VISION_FILTER_SUCCESS';
export const CANCEL_VISION_FILTER_API_TASK =
  'app/Dashboard/CANCEL_VISION_FILTER_API_TASK';

// <============================GLOBAL FILTERS (SPONSORS)=================================

export const SPONSORS_FILTER_PATTERN = 'app/Dashboard/SPONSORS_FILTER';
export const SPONSORS_FILTER_SUCCESS = 'app/Dashboard/SPONSORS_FILTER_SUCCESS';
export const CANCEL_SPONSORS_FILTER_API_TASK =
  'app/Dashboard/CANCEL_SPONSORS_FILTER_API_TASK';

// <============================GLOBAL FILTERS (ASSETS)=================================

export const ASSETS_FILTER_PATTERN = 'app/Dashboard/ASSETS_FILTER';
export const ASSETS_FILTER_SUCCESS = 'app/Dashboard/ASSETS_FILTER_SUCCESS';
export const CANCEL_ASSETS_FILTER_API_TASK =
  'app/Dashboard/CANCEL_ASSETS_FILTER_API_TASK';

// <============================GLOBAL FILTERS (VENUES)=================================

export const VENUES_FILTER_PATTERN = 'app/Dashboard/VENUES_FILTER';
export const VENUES_FILTER_SUCCESS = 'app/Dashboard/VENUES_FILTER_SUCCESS';
export const CANCEL_VENUES_FILTER_API_TASK =
  'app/Dashboard/CANCEL_VENUES_FILTER_API_TASK';

// <============================GLOBAL FILTERS (VISIONS)=================================

export const MARKET_FILTER_PATTERN = 'app/Dashboard/MARKET_FILTER';
export const MARKET_FILTER_SUCCESS = 'app/Dashboard/MARKET_FILTER_SUCCESS';
export const CANCEL_MARKET_FILTER_API_TASK =
  'app/Dashboard/CANCEL_MARKET_FILTER_API_TASK';



// <============================ STATS POLLING ==============================>

// 1) VISIONS
export const POLL_VISIONS_STATS = 'app/Dashboard/POLL_VISIONS_STATS';
export const POLL_VISIONS_STATS_SUCCESS =
  'app/Dashboard/POLL_VISIONS_STATS_SUCCESS';
export const POLL_VISIONS_STATS_FAILURE =
  'app/Dashboard/POLL_VISIONS_STATS_FAILURE';
export const STOP_POLLING_VISIONS_STATS =
  'app/Dashboard/STOP_POLLING_VISIONS_STATS';

// 2) BRANDS
export const POLL_BRANDS_STATS = 'app/Dashboard/POLL_BRANDS_STATS';
export const POLL_BRANDS_STATS_SUCCESS =
  'app/Dashboard/POLL_BRANDS_STATS_SUCCESS';
export const POLL_BRANDS_STATS_FAILURE =
  'app/Dashboard/POLL_BRANDS_STATS_FAILURE';
export const STOP_POLLING_BRANDS_STATS =
  'app/Dashboard/STOP_POLLING_BRANDS_STATS';

// 3) ASSETS
export const POLL_ASSETS_STATS = 'app/Dashboard/POLL_ASSETS_STATS';
export const POLL_ASSETS_STATS_SUCCESS =
  'app/Dashboard/POLL_ASSETS_STATS_SUCCESS';
export const POLL_ASSETS_STATS_FAILURE =
  'app/Dashboard/POLL_ASSETS_STATS_FAILURE';
export const STOP_POLLING_ASSETS_STATS =
  'app/Dashboard/STOP_POLLING_ASSETS_STATS';

// 4) VENUES
export const POLL_VENUES_STATS = 'app/Dashboard/POLL_VENUES_STATS';
export const POLL_VENUES_STATS_SUCCESS =
  'app/Dashboard/POLL_VENUES_STATS_SUCCESS';
export const POLL_VENUES_STATS_FAILURE =
  'app/Dashboard/POLL_VENUES_STATS_FAILURE';
export const STOP_POLLING_VENUES_STATS =
  'app/Dashboard/STOP_POLLING_VENUES_STATS';

// 5) MODELS
export const POLL_MODELS_STATS = 'app/Dashboard/POLL_MODELS_STATS';
export const POLL_MODELS_STATS_SUCCESS =
  'app/Dashboard/POLL_MODELS_STATS_SUCCESS';
export const POLL_MODELS_STATS_FAILURE =
  'app/Dashboard/POLL_MODELS_STATS_FAILURE';
export const STOP_POLLING_MODELS_STATS =
  'app/Dashboard/STOP_POLLING_MODELS_STATS';

// 6) CUMULATIVE
export const POLL_CUMULATIVE_STATS = 'app/Dashboard/POLL_CUMULATIVE_STATS';
export const POLL_CUMULATIVE_STATS_SUCCESS =
  'app/Dashboard/POLL_CUMULATIVE_STATS_SUCCESS';
export const POLL_CUMULATIVE_STATS_FAILURE =
  'app/Dashboard/POLL_CUMULATIVE_STATS_FAILURE';
export const STOP_POLLING_CUMULATIVE_STATS =
  'app/Dashboard/STOP_POLLING_CUMULATIVE_STATS';

// 7) PULSE
export const POLL_PULSE_STATS = 'app/Dashboard/POLL_PULSE_STATS';
export const POLL_PULSE_STATS_SUCCESS =
  'app/Dashboard/POLL_PULSE_STATS_SUCCESS';
export const POLL_PULSE_STATS_FAILURE =
  'app/Dashboard/POLL_PULSE_STATS_FAILURE';
export const STOP_POLLING_PULSE_STATS =
  'app/Dashboard/STOP_POLLING_PULSE_STATS';

// 8) CE
export const POLL_CE_STATS = 'app/Dashboard/POLL_CE_STATS';
export const POLL_CE_STATS_SUCCESS = 'app/Dashboard/POLL_CE_STATS_SUCCESS';
export const POLL_CE_STATS_FAILURE = 'app/Dashboard/POLL_CE_STATS_FAILURE';
export const STOP_POLLING_CE_STATS = 'app/Dashboard/STOP_POLLING_CE_STATS';

// 9) KPI
export const POLL_KPI_STATS = 'app/Dashboard/POLL_KPI_STATS';
export const POLL_KPI_STATS_SUCCESS = 'app/Dashboard/POLL_KPI_STATS_SUCCESS';
export const POLL_KPI_STATS_FAILURE = 'app/Dashboard/POLL_KPI_STATS_FAILURE';
export const STOP_POLLING_KPI_STATS = 'app/Dashboard/STOP_POLLING_KPI_STATS';

// <============================ LIVE API's  ==============================>

// 1) VISIONS
export const GET_LIVE_VISIONS_CONNECT = 'app/Dashboard/LIVE_VISIONS_CONNECT';
export const GET_LIVE_VISIONS_DISCONNECT =
  'app/Dashboard/LIVE_VISIONS_DISCONNECT';

// 2) SPONSORS
export const GET_LIVE_SPONSORS_CONNECT = 'app/Dashboard/LIVE_SPONSORS_CONNECT';
export const GET_LIVE_SPONSORS_DISCONNECT =
  'app/Dashboard/LIVE_SPONSORS_DISCONNECT';

// 3) ASSETS
export const GET_LIVE_ASSETS_CONNECT = 'app/Dashboard/LIVE_ASSETS_CONNECT';
export const GET_LIVE_ASSETS_DISCONNECT =
  'app/Dashboard/LIVE_ASSETS_DISCONNECT';

// 4) VENUES
export const GET_LIVE_VENUES_CONNECT = 'app/Dashboard/LIVE_VENUES_CONNECT';
export const GET_LIVE_VENUES_DISCONNECT =
  'app/Dashboard/LIVE_VENUES_DISCONNECT';

// 5) MODELS
export const GET_LIVE_MODELS_CONNECT = 'app/Dashboard/LIVE_MODELS_CONNECT';
export const GET_LIVE_MODELS_DISCONNECT =
  'app/Dashboard/LIVE_MODELS_DISCONNECT';

// 6) TIMELINE
export const GET_LIVE_TIMELINE_CONNECT = 'app/Dashboard/LIVE_TIMELINE_CONNECT';
export const GET_LIVE_TIMELINE_DISCONNECT =
  'app/Dashboard/LIVE_TIMELINE_DISCONNECT';

// 7) PULSE
export const GET_LIVE_PULSE_CONNECT = 'app/Dashboard/LIVE_PULSE_CONNECT';
export const GET_LIVE_PULSE_DISCONNECT = 'app/Dashboard/LIVE_PULSE_DISCONNECT';

// 8) CONTINOUS EXP
export const GET_LIVE_CE_CONNECT = 'app/Dashboard/LIVE_CE_CONNECT';
export const GET_LIVE_CE_DISCONNECT = 'app/Dashboard/LIVE_CE_DISCONNECT';

// 9) KPI
export const GET_LIVE_KPI_CONNECT = 'app/Dashboard/LIVE_KPI_CONNECT';
export const GET_LIVE_KPI_DISCONNECT = 'app/Dashboard/LIVE_KPI_DISCONNECT';

// <============================GRAPH INSIGHTS=================================

export const GRAPH_INSIGHTS_PATTERN = 'app/Dashboard/GRAPH_INSIGHTS_PATTERN';
export const GRAPH_INSIGHTS_SUCCESS = 'app/Dashboard/GRAPH_INSIGHTS_SUCCESS';
export const GRAPH_INSIGHTS_FAILIURE = 'app/Dashboard/GRAPH_INSIGHTS_FAILIURE';
export const CANCEL_GRAPH_INSIGHTS_API_TASK =
  'app/Dashboard/CANCEL_GRAPH_INSIGHTS_API_TASK';

// <============================SOCIAL=================================
// 1) SUB PLATFORM
export const GET_SOCIAL_SUBPLATFORM_PATTERN =
  'app/Dashboard/GET_SOCIAL_SUBPLATFORM_PATTERN';
export const GET_SOCIAL_SUBPLATFORM_SUCCESS =
  'app/Dashboard/GET_SOCIAL_SUBPLATFORM_SUCCESS';
export const GET_SOCIAL_SUBPLATFORM_FAILIURE =
  'app/Dashboard/GET_SOCIAL_SUBPLATFORM_FAILIURE';
export const CANCEL_GET_SOCIAL_SUBPLATFORM_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_SUBPLATFORM_API_TASK';

// 2) BASE REPORT
export const GET_SOCIAL_BASE_REPORT_PATTERN =
  'app/Dashboard/GET_SOCIAL_BASE_REPORT_PATTERN';
export const GET_SOCIAL_BASE_REPORT_SUCCESS =
  'app/Dashboard/GET_SOCIAL_BASE_REPORT_SUCCESS';
export const GET_SOCIAL_BASE_REPORT_FAILIURE =
  'app/Dashboard/GET_SOCIAL_BASE_REPORT_FAILIURE';
export const CANCEL_GET_SOCIAL_BASE_REPORT_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_BASE_REPORT_API_TASK';

// 3) SOCIAL DIGITAL_REPORT_TEMPLATE
export const GET_SOCIAL_DIGITAL_REPORT_TEMPLATE_PATTERN =
  'app/Dashboard/GET_SOCIAL_DIGITAL_REPORT_TEMPLATE_PATTERN';
export const GET_SOCIAL_DIGITAL_REPORT_TEMPLATE_SUCCESS =
  'app/Dashboard/GET_SOCIAL_DIGITAL_REPORT_TEMPLATE_SUCCESS';
export const GET_SOCIAL_DIGITAL_REPORT_TEMPLATE_FAILIURE =
  'app/Dashboard/GET_SOCIAL_DIGITAL_REPORT_TEMPLATE_FAILIURE';
export const CANCEL_GET_SOCIAL_DIGITAL_REPORT_TEMPLATE_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_DIGITAL_REPORT_TEMPLATE_API_TASK';

// 4) SOCIAL DIGITAL_REPORT
export const GET_SOCIAL_DIGITAL_REPORT_PATTERN =
  'app/Dashboard/GET_SOCIAL_DIGITAL_REPORT_PATTERN';
export const GET_SOCIAL_DIGITAL_REPORT_SUCCESS =
  'app/Dashboard/GET_SOCIAL_DIGITAL_REPORT_SUCCESS';
export const GET_SOCIAL_DIGITAL_REPORT_FAILIURE =
  'app/Dashboard/GET_SOCIAL_DIGITAL_REPORT_FAILIURE';
export const CANCEL_GET_SOCIAL_DIGITAL_REPORT_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_DIGITAL_REPORT_API_TASK';

// 5) SOCIAL TIMELINE
export const GET_SOCIAL_TIMELINE_PATTERN =
  'app/Dashboard/GET_SOCIAL_TIMELINE_PATTERN';
export const GET_SOCIAL_TIMELINE_SUCCESS =
  'app/Dashboard/GET_SOCIAL_TIMELINE_SUCCESS';
export const GET_SOCIAL_TIMELINE_FAILIURE =
  'app/Dashboard/GET_SOCIAL_TIMELINE_FAILIURE';
export const CANCEL_GET_SOCIAL_TIMELINE_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_TIMELINE_API_TASK';

// 5.1) SOCIAL TIMELINE_TEMPLATE
export const GET_SOCIAL_TIMELINE_TEMPLATE_PATTERN =
  'app/Dashboard/GET_SOCIAL_TIMELINE_TEMPLATE_PATTERN';
export const GET_SOCIAL_TIMELINE_TEMPLATE_SUCCESS =
  'app/Dashboard/GET_SOCIAL_TIMELINE_TEMPLATE_SUCCESS';
export const GET_SOCIAL_TIMELINE_TEMPLATE_FAILIURE =
  'app/Dashboard/GET_SOCIAL_TIMELINE_TEMPLATE_FAILIURE';
export const CANCEL_GET_SOCIAL_TIMELINE_TEMPLATE_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_TIMELINE_TEMPLATE_API_TASK';

  

// 6) SOCIAL HIGHLIGHTS
export const GET_SOCIAL_HIGHLIGHTS_PATTERN =
  'app/Dashboard/GET_SOCIAL_HIGHLIGHTS_PATTERN';
export const GET_SOCIAL_HIGHLIGHTS_SUCCESS =
  'app/Dashboard/GET_SOCIAL_HIGHLIGHTS_SUCCESS';
export const GET_SOCIAL_HIGHLIGHTS_FAILIURE =
  'app/Dashboard/GET_SOCIAL_HIGHLIGHTS_FAILIURE';
export const CANCEL_GET_SOCIAL_HIGHLIGHTS_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_HIGHLIGHTS_API_TASK';

// 7) SOCIAL RANK_TEMPLATE
export const GET_SOCIAL_RANK_TEMPLATE_PATTERN =
  'app/Dashboard/GET_SOCIAL_RANK_TEMPLATE_PATTERN';
export const GET_SOCIAL_RANK_TEMPLATE_SUCCESS =
  'app/Dashboard/GET_SOCIAL_RANK_TEMPLATE_SUCCESS';
export const GET_SOCIAL_RANK_TEMPLATE_FAILIURE =
  'app/Dashboard/GET_SOCIAL_RANK_TEMPLATE_FAILIURE';
export const CANCEL_GET_SOCIAL_RANK_TEMPLATE_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_RANK_TEMPLATE_API_TASK';

// 8) SOCIAL DIGITAL_REPORT
export const GET_SOCIAL_RANK_PATTERN = 'app/Dashboard/GET_SOCIAL_RANK_PATTERN';
export const GET_SOCIAL_RANK_SUCCESS = 'app/Dashboard/GET_SOCIAL_RANK_SUCCESS';
export const GET_SOCIAL_RANK_FAILIURE =
  'app/Dashboard/GET_SOCIAL_RANK_FAILIURE';
export const CANCEL_GET_SOCIAL_RANK_API_TASK =
  'app/Dashboard/CANCEL_GET_SOCIAL_RANK_API_TASK';


  // 9) SOCIAL DIGITAL_REPORT
export const GET_SOCIAL_DIGITAL_POST_PATTERN =
'app/Dashboard/GET_SOCIAL_DIGITAL_POST_PATTERN';
export const GET_SOCIAL_DIGITAL_POST_SUCCESS =
'app/Dashboard/GET_SOCIAL_DIGITAL_POST_SUCCESS';
export const GET_SOCIAL_DIGITAL_POST_FAILIURE =
'app/Dashboard/GET_SOCIAL_DIGITAL_POST_FAILIURE';
export const CANCEL_GET_SOCIAL_DIGITAL_POST_API_TASK =
'app/Dashboard/CANCEL_GET_SOCIAL_DIGITAL_POST_API_TASK';





// <============================DIGITAL=================================
// 1) DIGITAL SUB PLATFORM
export const GET_DIGITAL_SUBPLATFORM_PATTERN =
  'app/Dashboard/GET_DIGITAL_SUBPLATFORM_PATTERN';
export const GET_DIGITAL_SUBPLATFORM_SUCCESS =
  'app/Dashboard/GET_DIGITAL_SUBPLATFORM_SUCCESS';
export const GET_DIGITAL_SUBPLATFORM_FAILIURE =
  'app/Dashboard/GET_DIGITAL_SUBPLATFORM_FAILIURE';
export const CANCEL_GET_DIGITAL_SUBPLATFORM_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_SUBPLATFORM_API_TASK';

// 2) DIGITAL BASE REPORT
export const GET_DIGITAL_BASE_REPORT_PATTERN =
  'app/Dashboard/GET_DIGITAL_BASE_REPORT_PATTERN';
export const GET_DIGITAL_BASE_REPORT_SUCCESS =
  'app/Dashboard/GET_DIGITAL_BASE_REPORT_SUCCESS';
export const GET_DIGITAL_BASE_REPORT_FAILIURE =
  'app/Dashboard/GET_DIGITAL_BASE_REPORT_FAILIURE';
export const CANCEL_GET_DIGITAL_BASE_REPORT_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_BASE_REPORT_API_TASK';

// 3)  DIGITAL_REPORT_TEMPLATE
export const GET_DIGITAL_REPORT_TEMPLATE_PATTERN =
  'app/Dashboard/GET_DIGITAL_REPORT_TEMPLATE_PATTERN';
export const GET_DIGITAL_REPORT_TEMPLATE_SUCCESS =
  'app/Dashboard/GET_DIGITAL_REPORT_TEMPLATE_SUCCESS';
export const GET_DIGITAL_REPORT_TEMPLATE_FAILIURE =
  'app/Dashboard/GET_DIGITAL_REPORT_TEMPLATE_FAILIURE';
export const CANCEL_GET_DIGITAL_REPORT_TEMPLATE_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_REPORT_TEMPLATE_API_TASK';

// 4)  DIGITAL_REPORT
export const GET_DIGITAL_REPORT_PATTERN =
  'app/Dashboard/GET_DIGITAL_REPORT_PATTERN';
export const GET_DIGITAL_REPORT_SUCCESS =
  'app/Dashboard/GET_DIGITAL_REPORT_SUCCESS';
export const GET_DIGITAL_REPORT_FAILIURE =
  'app/Dashboard/GET_DIGITAL_REPORT_FAILIURE';
export const CANCEL_GET_DIGITAL_REPORT_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_REPORT_API_TASK';

// 5) DIGITAL TIMELINE
export const GET_DIGITAL_TIMELINE_PATTERN =
  'app/Dashboard/GET_DIGITAL_TIMELINE_PATTERN';
export const GET_DIGITAL_TIMELINE_SUCCESS =
  'app/Dashboard/GET_DIGITAL_TIMELINE_SUCCESS';
export const GET_DIGITAL_TIMELINE_FAILIURE =
  'app/Dashboard/GET_DIGITAL_TIMELINE_FAILIURE';
export const CANCEL_GET_DIGITAL_TIMELINE_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_TIMELINE_API_TASK';

// 5.1) DIGITAL TIMELINE_TEMPLATE
export const GET_DIGITAL_TIMELINE_TEMPLATE_PATTERN =
  'app/Dashboard/GET_DIGITAL_TIMELINE_TEMPLATE_PATTERN';
export const GET_DIGITAL_TIMELINE_TEMPLATE_SUCCESS =
  'app/Dashboard/GET_DIGITAL_TIMELINE_TEMPLATE_SUCCESS';
export const GET_DIGITAL_TIMELINE_TEMPLATE_FAILIURE =
  'app/Dashboard/GET_DIGITAL_TIMELINE_TEMPLATE_FAILIURE';
export const CANCEL_GET_DIGITAL_TIMELINE_TEMPLATE_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_TIMELINE_TEMPLATE_API_TASK';

  

// 6) DIGITAL HIGHLIGHTS
export const GET_DIGITAL_HIGHLIGHTS_PATTERN =
  'app/Dashboard/GET_DIGITAL_HIGHLIGHTS_PATTERN';
export const GET_DIGITAL_HIGHLIGHTS_SUCCESS =
  'app/Dashboard/GET_DIGITAL_HIGHLIGHTS_SUCCESS';
export const GET_DIGITAL_HIGHLIGHTS_FAILIURE =
  'app/Dashboard/GET_DIGITAL_HIGHLIGHTS_FAILIURE';
export const CANCEL_GET_DIGITAL_HIGHLIGHTS_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_HIGHLIGHTS_API_TASK';

// 7) DIGITAL RANK_TEMPLATE
export const GET_DIGITAL_RANK_TEMPLATE_PATTERN =
  'app/Dashboard/GET_DIGITAL_RANK_TEMPLATE_PATTERN';
export const GET_DIGITAL_RANK_TEMPLATE_SUCCESS =
  'app/Dashboard/GET_DIGITAL_RANK_TEMPLATE_SUCCESS';
export const GET_DIGITAL_RANK_TEMPLATE_FAILIURE =
  'app/Dashboard/GET_DIGITAL_RANK_TEMPLATE_FAILIURE';
export const CANCEL_GET_DIGITAL_RANK_TEMPLATE_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_RANK_TEMPLATE_API_TASK';

// 8) DIGITAL DIGITAL_REPORT
export const GET_DIGITAL_RANK_PATTERN = 'app/Dashboard/GET_DIGITAL_RANK_PATTERN';
export const GET_DIGITAL_RANK_SUCCESS = 'app/Dashboard/GET_DIGITAL_RANK_SUCCESS';
export const GET_DIGITAL_RANK_FAILIURE =
  'app/Dashboard/GET_DIGITAL_RANK_FAILIURE';
export const CANCEL_GET_DIGITAL_RANK_API_TASK =
  'app/Dashboard/CANCEL_GET_DIGITAL_RANK_API_TASK';


  // 9) DIGITAL DIGITAL_REPORT
export const GET_DIGITAL_POST_PATTERN =
'app/Dashboard/GET_DIGITAL_POST_PATTERN';
export const GET_DIGITAL_POST_SUCCESS =
'app/Dashboard/GET_DIGITAL_POST_SUCCESS';
export const GET_DIGITAL_POST_FAILIURE =
'app/Dashboard/GET_DIGITAL_POST_FAILIURE';
export const CANCEL_GET_DIGITAL_POST_API_TASK =
'app/Dashboard/CANCEL_GET_DIGITAL_POST_API_TASK';
